use_frameworks!

target 'ErrorHandler_Example' do
  pod 'SNErrorHandler', :path => '../'
  pod 'SNErrorHandler/Rx', :path => '../'

  target 'ErrorHandler_Tests' do
    inherit! :search_paths
		pod 'RxBlocking'
		pod 'RxTest'
    
  end
end
